### ISSUE TITLE
Update definition of "Sequence"s in GlassBR's MIS

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#109]
Should the definition of sequences be updated to "Sequences are lists filled with **ordered** elements of the same data type"?
https://github.com/smiths/caseStudies/blob/75f88389777a2b76422e691ef34065f505ad411f/CaseStudies/glass/docs/Design/MIS/glassbr_mis.tex#L103

Although it is known that sequences are ordered, perhaps making it explicit will be beneficial?

**Comment by smiths** [comment]
The word list is supposed to convey your intended meaning, but I agree that it falls short.  Your definition doesn't quite work either, since it implies that the element themselves have a natural ordering.  From the Wikipedia page for sequences, I suggest the following definition:

"Sequence are lists that represents a countable number of ordered values, where the same value may occur more than once."

This is very explicit about the fact that the same value can occur more than once, which usually helps people understand that sets and sequences are different.

**Comment by niazim3** [comment]
I added "of the same data type" from the original definition to the new definition. If that is alright, this issue can be closed.

**Comment by smiths** [comment]
Sounds good.  Yes, this issue can be closed.
