### ISSUE TITLE
MAX_SIZE value derivation in MIS?

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#111]
Out of curiosity, why was the constant 100 chosen to be = `MAX_SIZE` in the MIS for the ContoursADT module?
https://github.com/smiths/caseStudies/blob/75f88389777a2b76422e691ef34065f505ad411f/CaseStudies/glass/docs/Design/MIS/glassbr_mis.tex#L870

If there isn't a particular reason and it's just arbitrary, then the MIS is fine, but if not, then the rationale should be mentioned.

**Comment by smiths** [comment]
I  like the way you think @niazim3.  The number is arbitrary.  It is just a number much larger than the number of curves in the GlassBR figures.  Thinking about it further though, the real reason that constant is in there is as an example for the 2ME3 class.  It really isn't necessary.  The number of functions in the ContoursADT is really only limited by the memory.  The module should really be generic, so that it can be used in different contexts, so why have an arbitrary limit.

Can  you edit the MIS to remove the mention of MAX\_SIZE?  I'll create a new issue.
