### ISSUE TITLE
Review of SRS data constraints vs Input Module exceptions

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#129]
I compared the input data constraints table in the SRSs against the `Input.verify_params()` documentation 
![image](https://user-images.githubusercontent.com/28247301/43008135-3d70b690-8c08-11e8-99d4-207e10c6f11b.png)
and noticed the following discrepancies:
### 1. (Within Drasil) The physical constraint for _a_ : `a <= b` conflicts with that of _b_: `0 < b < a`. Can `a = b` or not? If _a_ cannot be `=` to _b_, a new error should be defined and an issue should be opened in the Drasil repo about making the change, otherwise, MIS list is fine.
![image](https://user-images.githubusercontent.com/28247301/43007897-acd81d1c-8c07-11e8-88f4-d1b8c83fda92.png)
### 3. Is _AR >= 0_ (MIS) or _AR >= 1_ (manual SRS)?

(Below is the table for data constraints from the manual version for reference 
![image](https://user-images.githubusercontent.com/28247301/43008386-ec5c3b84-8c08-11e8-909c-a362bc0361e9.png).)

**Comment by smiths** [comment]
The constraints for w are discussed in:
https://github.com/JacquesCarette/Drasil/issues/924
The constraint for AR should be >= 1.0 (not 0).

The constraints in Drasil related to a and b are confusing.  That is why the aspect ratio AR has been added to the constraints.  It should be easier to understand with AR.  a can be equal to b.  That just means a square plate.  That error was introduced into Drasil at some point.

Yes, AR should be added to Drasil.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith is there anything else that should be added to this checklist: 
- [ ] `AR` needs to be fixed in the manual SRS to be (AR >= 1.0)
- [ ] `a` can be equal to `b`, therefore the data constraints for `b` should be (0 < b <= a) (Both manual and Drasil must be changed)
- [ ] `AR` must be propagated to Drasil

**Comment by elwazana** [comment]
This is the `b` constraints fix in the manual SRS:
2b1252b09fb72e3c8b3611268949e68a02ae2782
![image](https://user-images.githubusercontent.com/35268928/43105523-2f9f6582-8ea3-11e8-8b33-387a43307717.png)

**Comment by smiths** [comment]
Looks good to me.  I believe there is another issue for this, but the mm units also need to be changed to m.

**Comment by smiths** [comment]
Yes, in the definition of AR, a >= b.

**Comment by elwazana** [comment]
This is the last fix for `a` and `b`:
![image](https://user-images.githubusercontent.com/35268928/43162413-ea9c8922-8f58-11e8-88f9-7ad11be6c08d.png)

I've started to propagate the `AR` constraints into the Data Constraints for Drasil:
![image](https://user-images.githubusercontent.com/35268928/43162470-1cef32da-8f59-11e8-8938-8b9d570db949.png)

@smiths Where do I retrieve the `Typical Value` and `Uncert.` for `AR` from? 

Additionally none of the listed `Typical Values` or `Uncert.` really state where they are retrieved from which seems like a traceability issue (Both Drasil and Manual).

Also should `AR` have its own row in the Data Constraint table? In the manual its weaved into the rows of `a` and `b`:
Manual:
![image](https://user-images.githubusercontent.com/35268928/43163402-0c195d70-8f5c-11e8-91e6-a8a796621750.png)

This would be difficult to do in Drasil because Drasil can't have the constraints of two different symbols in the same row.

**Comment by smiths** [comment]
Great questions.  For the typical value of AR, I suggest 1.5.  For uncertainty, use 10%.  It would be great to have traceability to the typical values and uncertainty, but we don't really have a source for this information.  The uncertainty in particular is rarely discussed.  The SRS is intended to get people to think about uncertainty going forward, but it isn't standard procedure today.

I like the idea of AR having its own row.  As you said, it helps Drasil and it is also cleaner in the manual version.  Please create a new issue for this.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, here is the final table with the modifications to `b` and `AR` completed:
https://github.com/JacquesCarette/Drasil/commit/d3275fc06364b2177c4a17c1e273aa8fe8bc2aad
![image](https://user-images.githubusercontent.com/35268928/43211631-fc48a7d0-8fff-11e8-9c51-aabead9d2734.png)
