### ISSUE TITLE
Differences in generated/manual MIS Introduction

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#143]
- [x] In the first sentence, "Module Interface **Specification (MIS)**" is preferred.
- [x] In manual (right), the SRS should be called "**Software** Requirement**s** Specification~~s~~", as in the title of the SRS.

![intro](https://user-images.githubusercontent.com/35857611/43856463-9a564506-9b16-11e8-8a46-a6e77555bab2.png)

**Comment by smiths** [comment]
@samm82 I agree that SRS should stand for Software Requirements Specification.  We aren't writing a System, since there isn't a hardware component, or interacting, independent, software entities.  As for as MIS goes, I would like to leave it singular.  That is the way the Parnas uses it, and I'm not going to go against Parnas without a really good reason.  😄  Please make the changes for the SRS, but you can leave the MIS part as it is.  Can you please add (MIS) after Module Interface Specification in the first line.
