### ISSUE TITLE
SRS TableOfContents Issue

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#159]
1- In the table of contents you must refer to the “References” and “Appendix”. 
2-Although in the template "TableOfContent" has been placed after "ReferenceMaterial", I think it should be before this section if Dr.Smith would make an agreement.

**Comment by bmaclach** [comment]
There is no "Appendix" listed in the table of contents because this SRS does not have an appendix. I added "References" to the table of contents with commit a440a5d7f7bc95d1ea0115c1ef23a4cc654a07ca.

As for item 2, let's wait for feedback from @smiths since it would be a change to the template. I think the reason "Reference Material" appears before the table of contents is to be consistent with the standard of having the table of contents at the end of the front matter (with roman-numeral page numbers).

**Comment by vajihehm** [comment]
@bmaclach Thank you Brooks. This commit addressed item 1. So, Let 's wait for feedback from @smiths  to close this issue completely.

**Comment by smiths** [comment]
I apologize for the delay in replying.  Let's leave the template as it is.  :-)
