### ISSUE TITLE
SRS User Characteristics Issue

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#162]
In the User Characteristics section, is it required that user be familiar with “cohesion, effective angle of friction, and unit weight”?  I think these material would be too detailed and user is not required to have this knowledge.

**Comment by bmaclach** [comment]
Originally, the document simply said the user should be "familiar with material properties", which I thought was too vague. I added the specific material properties that SSP uses to make it more clear. I do think it is important for the user to be familiar with these properties because they are all inputs to the system which the user must provide. If the user doesn't know what cohesion is, for example, they will not be able to effectively use SSP because one of their input values would not be well-informed.

Let me know if you agree with this, @vajihehm. If so, I'll go ahead and close the issue.

**Comment by vajihehm** [comment]
@bmaclach Considering that you are more than me working with the user requirements, I agree with that, So, we can close this issue.
