### ISSUE TITLE
SRS Goal Statement Question

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#163]
Has been the goal  “Determine the displacement of the slope” split into following goals :  
GS3:  Determine the interslice normal force between each pair of vertical slices of the slope.
GS4: Determine the interslice shear force between each pair of vertical slices of the slope.

**Comment by bmaclach** [comment]
The goal about determining displacement was removed because we adjusted the scope of the project to not include RFEM analysis, which is how the displacement was being determined. SSP no longer is concerned with determining the displacement.

The new goals GS3 and GS4 were added simply because they are related to the outputs of SSP. I believe these goals were mistakenly left out of the original document.
