### ISSUE TITLE
SRS System Constraint Question

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#165]
The Morgenstern-Price method has been considered as a system constraint. I am not sure about if it is considered as a system constraint or not. Is this method as a special software which would be needed to install ?

**Comment by bmaclach** [comment]
Using the Morgenstern-Price method does not lead to any external software being required. There are many different sets of equations that could be used to solve a slope stability analysis problem. We are restricting SSP to only use the equations related to the Morgenstern-Price method. I would still say that it is a system constraint because it restricts the equations we use to solve the problem. 

Let me know if you are satisfied by this explanation, @vajihehm. If so, I'll close the isssue.

**Comment by vajihehm** [comment]
@bmaclach That is ok. Your reasons convinced me. So, we can close this issue.
