### ISSUE TITLE
MIS Imported Access Programs Subsection

### ISSUE THREAD

**Issue by bmaclach** [smiths/caseStudies#213]
The MIS for SSP has a subsection under "Uses" for "Imported Access Programs", shown below.
![image](https://user-images.githubusercontent.com/18634568/48424780-5b8a3c80-e731-11e8-94c4-0ac2f4571d01.png)

Most of the examples I've looked at do not include this subsection. Instead, the "Uses" subsection simply lists the names of the other modules that are used by the module. The only other example I could find that has this subsection is noPCM, but in noPCM the section contains different information (instead of "Uses", "Passes", and "Receives", noPCM shows "Uses" and "Imports").

Normally I would update this to match the template and other examples, but since in this case that would mean removing information, I wanted to double check first that it is a good change. Should I remove these subsections and instead list the module names that are used, as is done in other examples?

**Comment by smiths** [comment]
Thanks for the question @bmaclach.  I was not aware of this part of the specification in SSP.  Am I correct that the list of passes and receives are inputs and outputs to the different access programs?  This seems like redundant information, since each access program lists its own inputs and outputs.

I think of the uses clause like imports in Python.  In Python you can import everything from a module or import some of the access programs.  The Python notation is about namespace, but some times it is nice to list just those access programs that will be needed.

In your case, if I am correct that the list of passes and receives are input and output arguments, I suggest that you delete this information.  I'm glad you are checking with me, but I cannot think of any examples of design documentation where this information would be documented twice (once in the "header" like this, and once for the access program syntax.  This seems like an unnecessary maintenance headache.

Changing so that uses just list the modules that are used for the module in question should be fine.

If I misunderstood the meaning of passes and receives, please let me know.

**Comment by bmaclach** [comment]
You understood correctly. I'll go ahead and update the "Uses" section as discussed. Thank you!
