### ISSUE TITLE
PCM SRS - Software Diameter constraint makes no sense

### ISSUE THREAD

**Issue by JacquesCarette** [smiths/caseStudies#26]
Table 2 has D/L_min <= D/L <= D/L_max.

First, this does not constrain D at all (given that it is positive), since it can be eliminated.

Second, since L_min <= L <= L_max, this is 'backwards' !

No idea what the right constraints ought to be.  I will, for now, eliminate this constraint from the SWHS example in the Drasil repo, until this can be figured out.

**Comment by smiths** [comment]
Hi Jacques.  What is written in the SRS is wrong.  The idea was to constrain the aspect ratio of the tank.  That is (D/L)_min <= D/L <= (D/L)_max.  There are bounds on the ratio of D to L.  If D and L are constrained separately, then it is possible to have cases like D_min with an L_max, which would undoubtedly be a poorly shaped vessel (very skinny and tall).

Is it possible to constrain ratios like this in Drasil?  As a temporary step, we could just constrain D, but at some point we will need to think about constraints that are based on a combination of inputs.  (The same thing happens in beam theory.  Whether thin or thick beam theory applies is determined by the ratio of the beam's length to depth.)

**Comment by JacquesCarette** [comment]
Yes, we can do that. The simplest way is to create a quantity for the ratio D/L, and the constrain that to be in a range.

I take it the SRS first needs to be fixed to make the math be correct, and then we can encode it in Drasil?  In particular, even though (D/L)_min can be interpreted by humans, I think that particular 'notation' may hamper rather than help verification/certification efforts -- because it imposes too high an interpretation burden.

**Comment by smiths** [comment]
I've modified the SRS to replace the ratio D/L by the symbol R.  The changes are made in the following tex file:

https://github.com/smiths/swhs/blob/master/SRS/PCM_SRS.tex

All changes are indicated by the comment CHANGE, so that they are easy to find.  The ratio R is locally defined.  That is the R is defined inside the Table of constraints.  It doesn't really need to have a scope outside of this table (other than to be listed in the table of symbols).

If you agree with the change, we could assign the issue of updating the Drasil version of SWHS to @halonazhao.

**Comment by JacquesCarette** [comment]
Sorry, this got buried.  Looks good - and yes, makes sense to assign to whoever is currently working on SWHS.

**Comment by samm82** [comment]
Closed with JacquesCarette/Drasil#1061
