### ISSUE TITLE
Review SSP Documentation and Code

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#27]
Please review the SSP documentation and create at least 5 issues.

**Comment by niazim3** [comment]
Documentation to look at:

- [ ] SRS
- [ ] MG
- [ ] MIS

**Comment by niazim3** [comment]
Can this issue be closed?

**Comment by smiths** [comment]
Very thorough work @niazim3.  I will do my best to work through the issues you have created.  However, please do not close this issue.  I should have mentioned that you should also review the ssp code and any test cases.  I have edited the title to include an explicit mention of the code.

**Comment by niazim3** [comment]
The following minor updates were implemented in the commit range (40198a24a...166d01a) to contribute to this issue after directly comparing the Drasil and manual versions of the SRS:
- [x] add missing "the" in "Organization of Document"
- [x] match wording in problem description to match that of Drasil (since it sounds better)
- [x] add missing introduction for "Terminology and Definitions" from Drasil
- [x] update definitions of "tension" and "compression" to use "that" (like in Drasil) instead of "the" (since it akes more sense)
- [x] lowercase the word "interslice" in middle of "Physical System Description" text
- [x] update goal statements to be "GS#" instead of "G#" to match both Drasil and table of abbreviations infromation
- [x] add "UC | Unlikely Change" to table of abbreviations
- [x] italicize "x,y" in "(x, y)" of assumption 1

@smiths, can you please ensure that the changes in that commit range are good to go? They were on the straightforward side of things, which is why they were quickly implemented. 
Please note: I realized after starting their implementation that a PR probably would've been better for review, which is why any other changes of this nature I'll make in a small PR.

**Comment by smiths** [comment]
The changes are fine.  Thank you for making them.  I believe you can close this issue now.
