### ISSUE TITLE
Grammatical Errors in SRS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#30]
### CaseStudies
  - [x] Commas
  - [x] Spaces
  - [x] Periods
  - [x] Semicolons
  - [x] Singular/Plural
  - [x] Spelling
### Drasil
  - [x] Commas
  - [x] Spaces 
  - [x] Periods
  - [x] Semicolons
  - [x] Singular/Plural
  - [x] Spelling

The following errors should be fixed [here](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Documentation/SRS/glassbr_srs.tex):

### Missing spaces
     - line 287: "...civil engineering.In addition, reviewers should be familiar with the applicable..." should have a space between 'engineering.' and 'In'

**Comment by samm82** [comment]
@smiths Can we start to fix some of these issues?

**Comment by smiths** [comment]
I'm sorry @samm82, but please do not start to fix the issues yet.  I'm sure that I'll agree with most of them and the fixes will be quick, but we are at the point now where there are consequences for every change.  Anything fixed in the manual version also has to be fixed in the stable (Drasil) version.  I want to make sure we handle this very systematically. 

You and your colleagues (@niazim3 and @samm82) have been doing such a great job of identifying issues that I am behind in reviewing.  While you are waiting, please make sure that your issues are complete.  Whenever possible, include everything in the issue so that I don't have to open the original document.

If you need something to do, please send me an e-mail and I'll create another issue for you to address.

**Comment by smiths** [comment]
I am now going to go through your proposed list of edits.  I apologize for the delay.  As you can likely deduce, I tend to work on my e-mail stack from the top down.  😄 

When I ask you to proceed with the change, please make it in both the manual and the Drasil versions.

I am not done editing yet, but I am going to save the current text because I've had some bad experiences of losing edits midway through and I don't have time to finish it right now.

The following errors should be fixed [here](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/docs/SRS/glassbr_srs.tex) (fixed link):

- [ ] Missing commas where they are required for syntax or for clarity 
     - line 146: "Throughout this document SI (Syst\`{e}me International d'Unit\'{e}s) is employed..." should have a comma after 'document'.  [I'm sorry, but I disagree on this change.  We can leave the text as it is.]
     - line 249: "explosion. The software, herein called \progname\ aims to predict the blast risk" should have a comma after '\progname\' [Agreed.  Please make this change]
     - line 253: "...fulfil, the scope of the requirements and the organization of the document: what..." should have a comma after 'requirements' [Agreed.  Please make this change]
     - lines 371-372 "...type input includes parameters like weight of charge, TNT equivalent factor and
stand off distance from the point of explosion...." should have a comma after 'factor'
     - lines 380-381 "...return true then it's shown that the glass slab is safe to use, else if both
return false then the glass slab is considered unsafe...." should have commas after 'true' and 'false'
     - lines 557-559: "\label{A_LDF}:] With reference
   to A\ref{ass_val} the value of load distribution factor (LDF) is a constant
   in \progname." should have a comma after 'A\ref{ass_val}'

- [ ] Missing spaces
     - line 287: "...civil engineering.In addition, reviewers should be familiar with the applicable..." should have a space after 'engineering.' and 'In'
     - line 420: "...A flat,monolithic, glass lite which has uniform..." should have a space between 'flat,' and 'monolithic'
     - line 426: "...the edge compression not less than 67 MPa (9700 psi)as defined in \cite{C1048}." should have a space between 'psi)' and 'as'
     - line 431: "...greater than 52 MPa (7500 psi)as defined in \cite{C1048}." has the same issue as 426

- [ ] Missing periods
     - at the end of lines 422, 437, 444, 447, 451, and 458
     - line 484: "\item{PS1:} Glass slab" should be written as "\item{PS1:} The glass slab."

- [ ] Separate sentences where a semicolon would add clarity
     - line 547: "...consideration is assumed to be a single lite.  Hence the value of LSF is equal..." should be "...single lite; hence, the..."

- [ ] Inconsistent singular/plural
     - lines 395: "...inputs to give out the outputs which predicts whether the glass slab can..." should be "...outputs which predict whether..."
     - line 551: "... conditions for the glass slab is assumed to be 4-sided support for all..." - either 'conditions' should be singular or 'is' should be 'are'

- [ ] Minor spelling errors 
     - line 456: "...load sharing between the double glazing, of equal or different thickness's and..." should have 'thicknesses'
     - line 485: "...\item{PS2:} The point of explosion.  Where the bomb, or any man made explosive..." should have 'man-made'
     - line 618: "... & $q$ (also refereed as the demand) is the 3 second equivalent pressure, as..." should have 'referred'
(6.1.1, 6.1.2, 6.2.2)

**Comment by samm82** [comment]
For the first missing comma instance, I'm pretty sure there should technically be a comma there. "Throughout this document" is a dependent clause, while the rest of the sentence is the independent clause, so since it comes at the beginning of the sentence, it should be separated by a comma.

The missing periods are in the list of Terminology and Definitions (ie. at the ends of (a), (b), (d), (f)):
![missing periods](https://user-images.githubusercontent.com/35857611/42235234-2b76cef2-7ec5-11e8-8aa7-5bfaf8de1b67.png)
Also I apologize for the awful format of this issue - after having worked on GitHub for a few months, this is appalling 😆

**Comment by smiths** [comment]
@samm82, please add the periods as you suggested.

As for the start of the document, I really like that you are using grammar rules.  My comment was based on "it doesn't sound right with the comma."  I was about to acquiesce to your superior grammar knowledge, when I looked up dependent noun clauses.  I believe in the case of dependent noun clauses, the comma is not normally used when the dependent clause comes first.  I base this on a quick reading of:

https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_n&page=9AqfxfeEY5lI.html

**Comment by samm82** [comment]
Never mind - you're totally right. My bad

**Comment by samm82** [comment]
Also, "This section explains the purpose the document is designed to fulfil, the scope of the requirements and the organization of the document:" Fulfil is technically correct, but in North America, fulfill is used more often - which do you prefer? @smiths

**Comment by smiths** [comment]
I definitely prefer fulfill.  If you want to fulfill my wish, please change fulfil to fulfill.  😄

**Comment by samm82** [comment]
For the spacing issues, I could "hardcode" them by changing:
``appStanddIR = foldlSent [S "In addition" `sC` plural reviewer,``
to 
``appStanddIR = foldlSent [S " In addition" `sC` plural reviewer,``,
but I'm assuming that there is a fundamental issue that could be fixed. @smiths

**Comment by samm82** [comment]
Can be closed with merge of JacquesCarette/Drasil#800
