### ISSUE TITLE
SSP : Grammatical/Formatting Fixes Needed

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#35]
(Issue #27)

## Grammar, Punctuation, and Spelling :

1. section 4.1 (Problem Description)--> missing apostrophe from "slopes" (see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L438)
2. section 4.1.1 (Terminology)--> possible confused word ("dominate" should be "dominant")? (see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L471)
3. section 4.1.3 (Goal Statements) --> unnecessary capitalization of 's' and 'f'? (see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L563)
4. T2 description --> awkward wording and misuse of commas 
![image](https://user-images.githubusercontent.com/28247301/39632893-59fb3e0e-4f84-11e8-92a4-58ad38b68547.png)
(see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L690-L695)
5. T3 description --> misuse of comma 
![image](https://user-images.githubusercontent.com/28247301/39632976-a84ae87a-4f84-11e8-9020-092ffbf078ea.png) (see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L735)
6. T5 description --> awkward wording 
![image](https://user-images.githubusercontent.com/28247301/39633182-3ec8998c-4f85-11e8-90f3-10a23590162b.png) (see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L805-L808)
7. section 4.2.6 (Data Constraints) --> instances of "vertices's" and "vertexes" should be changed to "vertices'" and "vertices" 
![image](https://user-images.githubusercontent.com/28247301/39633513-394e7430-4f86-11e8-8fc7-9e7e10fe9735.png)
(https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L2972-L3005)
8. IM4 --> missing a comma between input symbols
(see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L2627-L2628)
9. "Stifness Matrixes" --> "Stiffness Matrices" (see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L1954)

## Formatting: 

- [ ] section 4.2.1 (Assumptions) --> "The numbers given in the square brackets..." there are no square brackets with numbers in this section, can probably remove this sentence completely or add the numbers
![image](https://user-images.githubusercontent.com/28247301/39633927-5bdef55a-4f87-11e8-89f1-99fcf518991a.png)
(see https://github.com/smiths/caseStudies/blob/f1a7a499e34775b89265c3f804645ee5a56248c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L576-L582)

**Comment by smiths** [comment]
Unless noted otherwise, please make your proposed changes.   You'll need to also check in Drasil to make sure the changes are consistent.

4. T2 description --> awkward wording and misuse of commas

Remove the comma and delete the text you have highlighted in orange.  I think I know what the text is there, but it really isn't necessary, since we already know this is a 2D problem.

6. T5 description --> awkward wording

Replace with "Stiffness $K$ is the resistance of a body to deformation by displacement $\delta$ when ..."

section 4.2.1 (Assumptions) --> "The numbers given in the square brackets..." 

We don't want to delete this text, since eventually there should be traceability information given in brackets.  You could modify the text to indicate that there isn't currently any traceability information, but it will be added in the future.

**Comment by niazim3** [comment]
@smiths Can you please review the changes made (easily viewable [here](https://github.com/smiths/caseStudies/compare/a777ad482defe46dbf5e78c29031dae8b0714918...18a6ee2fed61de82eed12b51bb4929f6d4e544c6))?

Specifically,

1. was number 4 done properly (was the correct portion of the description removed)?
2. I changed the text under physical constraint to more than just stated above ("vertices are monotonic" instead of "vertices' monotonic"), is that alright?
3. Approval of sentence added under the assumptions section. This a change that has not yet been implemented in Drasil, as such a change will affect all examples. Is it necessary to make this update anyhow? When we're currently working on traceability and referencing with the introduction of `Label`s?

Thanks!

**Comment by smiths** [comment]
Great work.  I really like how you have presented the commits in an easy to view format.  In response to your questions:

- Yes, your version of 4 (with the equal to $0$ part) is correct
- For "vertices are monotonic" is better than the previous text.  The actual constraint is that the location of the vertices are monotonically increasing, but this is too much text for the table, and it is properly expanded elsewhere.
- With respect the the sentence about assumption traceability, I don't like the idea of propagating this temporary text to all of the case studies.  I only suggested it so that we weren't misleading the reader, but at the same time, we weren't deleting text we will need in the future.   Can you have a look to fill in the traceability information for one assumption?  That way the original text will be correct, and we don't need to make the proposed change.

**Comment by niazim3** [comment]
I believe this issue can be closed upon approval/discussion on changes made in 79088b8.

**Comment by smiths** [comment]
Yes, we can close this issue.
