### ISSUE TITLE
SSP : SRS Symbol Clarifications required for consistency

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#39]
(Issue #27)

Under section 1.2 specifically :
- [x] _F_x_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L172)
- [x] _F_y_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L174)
- [x] ~~_a_ missing description~~ See comments below (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L154)
- [x] ~~_A_ missing description~~ See comments below (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L156)
- [x] _C1_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L162)
- [x] _C2_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L164)
- [ ] _lowercase kappa_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L288)
- [x] can _M_'s description be improved to be more descriptive/defining? (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L210)
- [x] _lowercase sigma_ description : "plain" should be "plane"? (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L296)

Undefined/misdefined instances:
- [x] T3 describes cohesion _c_, which is a symbol not mentioned in the equation it is describing or in the table of symbols (should it be _c'_?) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L736)
- [x] _c_ is not defined (mentioned in section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3036)
- [x] _U_s_ in T3 not defined in table of symbols (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L733)
- [x] _lowercase phi_ not defined (mentioned in section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3038)
- [x] _(_lowercase gamma_)__wat_ not defined, meant to be _(_lowercase gamma_)__w_? (section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3045)

Other:
- [x] replace "deg" with actual symbol for consistency (section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3038-L3039)

**Comment by smiths** [comment]
I'll edit in my comments below:

Under section 1.2 specifically :
- [ ] _F_x_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L172)

I don't have a problem with the definition given.  An abstract definition is appropriate, since Fx is used for the general theory of equilibrium.  However, it should be $x$ component, not X component.

- [ ] _F_y_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L174)

Also seems fine as given.  However, it should be $y$ component, not Y component.

- [ ] _a_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L154)

$a$ comes from StolleGuo2008.  $a$ is a constant that ensures the denominator in the calculation of $K_t$ is not zero and $K_t >> k_t$.

At least in the short term, I do not really want to support the documentation of the rigid finite element method in SSP.  We don't want to put too much work into these aspects of the documentation.

- [ ] _A_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L156)

$A$ is also defined in StolleGuo2008.  As I mentioned above, we don't want to put too much work into the rigid finite element portion of the documentation.  You can say that A is a material property related to the interface stiffness in tension.

- [ ] _C1_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L162)

C1_i is the shear force at the interslice interface for slice i.

- [ ] _C2_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L164)

C2_i is the normal force at the interslice interface for slice i.

- [ ] _lowercase kappa_ missing description (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L288)

Does kappa even appear in the current documentation?  The parameter $A$ mentioned above is calculated from kappa (StolleAndGuo2008), but I don't think this equation is given in the document.

- [ ] can _M_'s description be improved to be more descriptive/defining? (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L210)

"Moment of a Body: assumed 2D allowing a scalar" isn't the best description.  It isn't the moment of a body, but the moment of a force.  I think we can just say "Moment of a force about a given axis".

- [ ] _E_ is used to denote both elastic modulus and interslice normal force, results in ambiguity (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L166-L169)

The interslice force should have a subscript.  This should help a bit with the ambiguity.  In the long run, a symbol other than E should be used for the interslice force.  E for Young's modulus is so standard that it would be a mistake to change it, but the interslice force can be with any a symbol, likely a different alphabetical character that isn't used elsewhere.

- [ ] _lowercase sigma_ description : "plain" should be "plane"? (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L296)

Yes, please make this change and check the Drasil version as well.

Undefined/misdefined instances:
- [ ] T3 describes cohesion _c_, which is a symbol not mentioned in the equation it is describing or in the table of symbols (should it be _c'_?) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L736)

Yes, is should be _c'_.

- [ ] _c_ is not defined (mentioned in section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3036)

Use _c'_ instead

- [ ] _U_s_ in T3 not defined in table of symbols (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L733)
- [ ] _lowercase phi_ not defined (mentioned in section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3038)
- [ ] _(_lowercase gamma_)__wat_ not defined, meant to be _(_lowercase gamma_)__w_? (section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3045)

Other:
- [ ] replace "deg" with actual symbol for consistency (section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3038-L3039)

**Comment by smiths** [comment]
Yes, I am fine with the FIXMEs.  There is a reasonable chance that we will remove mention of a and A completely, at least temporarily.

**Comment by niazim3** [comment]
(2 more points left to close this issue)

***

Re: Kappa is in the document:
![image](https://user-images.githubusercontent.com/28247301/41624865-f4353e78-73e4-11e8-8a3d-6c784d898621.png)
![image](https://user-images.githubusercontent.com/28247301/41624896-0caf692e-73e5-11e8-87bc-79b176eb9902.png)

It is in the same equation _A_ is in, so are they close enough in nature for kappa to also be left as a Fixme that will be removed with _a_ and _A_?

***
Re: In that case, _lowercase phi_ from (mentioned in section 5.1 (Functional Requirements)) (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3038) should actually be a _lowercase phi_' https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L302

**Comment by smiths** [comment]
Yes, make kappa a fix me.  Thank you.

**Comment by niazim3** [comment]
Since lowercase kappa is a fixme, all symbols originally mentioned have been discussed/updated.
