### ISSUE TITLE
Grammatical Errors in MG

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#41]
The following errors should be fixed [here](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Documentation/MG/glassbr_mg.tex).

- [x] Unclear wording (line 80: "After completing the first stage of the design, the Software Requirements..." could be rephrased: "...design, which is the Software Requirements..."
- [x] Extra word (line 95: "Designers: Once the module guide has been written, it ~~is~~ can be used to"
- [x] Unnecessarily short sentence (line 150: "...more complex. Sometimes this complexity is not necessary. Fixing some design..." could be rewritten as "...not necessary, and fixing some...")
- [x] Missing comma for clarity (line 296: "...properties, processing conditions, and numerical parameters.  The values can be..." should have a comma after 'conditions.')

**Comment by smiths** [comment]
I'll respond to the comments below.  Since this is for the MG, there is no need to make corresponding changes in the Drasil version.  Some (all?) of the line numbers will have changed, since I have been making edits to the MG.  You can always use search to find the text you are interested in.

The following errors should be fixed [here](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/docs/Design/MG/glassbr_mg.tex).

- [ ] Unclear wording (line 80: "After completing the first stage of the design, the Software Requirements..." could be rephrased: "...design, which is the Software Requirements..." [Agreed.  Please make the change.]
- [ ] Extra word (line 95: "Designers: Once the module guide has been written, it ~~is~~ can be used to" [Agreed.  Please make the change.]
- [ ] Unnecessarily short sentence (line 150: "...more complex. Sometimes this comple xity is not necessary. Fixing some design..." could be rewritten as "...not necessary, and fixing some...") [I agree that the current text is too choppy.  How about replacing "However, a general system is
more complex. Sometimes this complexity is not necessary. Fixing some design
decisions at the system architecture stage can simplify the software design." with "However, generality can introduce complexity, which can, at times, be avoided by explicitly fixing some decision decisions as unlikely changes."]
- [ ] Missing comma for clarity (line 296: "...properties, processing conditions, and numerical parameters.  The values can be..." should have a comma after 'conditions.') [I wonder if this was edited out?  I cannot find it.]

**Comment by samm82** [comment]
I cannot find the last issue either @smiths

**Comment by smiths** [comment]
Great.  Nice to see this issue closed.  Sorry for the delay.  😄
