### ISSUE TITLE
Glass-BR: Missing information in section 4 in SRS

### ISSUE THREAD

**Issue by deviprasad135** [smiths/caseStudies#43]
In section 4 it is mentioned that information about the system, identifies the interfaces between the system and its environment will be provided in that section, but no information about that is provided.
![section 4](https://user-images.githubusercontent.com/30101689/39760112-81e32c26-52a2-11e8-8d92-7fc86c6d77bc.PNG)

**Comment by smiths** [comment]
Great observation @deviprasad135.  You are correct that the "roadmap" text does not match the actual contents of the section.  I just checked and the same mistake exists in the generated code in Drasil.  The same mistake is also made in at least one of the other cases studies.  (I just saw the same mistake in the game physics example.)  The fix is not to delete the entries from the roadmap, but to fix GlassBR to follow the template it was supposed to follow.  We need to add a system context section.  We also might want to delete the "provides general information about the system."  I'll close this issue and create a new one asking you to write the system context section.
