### ISSUE TITLE
Glass-BR: Unclear Assumption

### ISSUE THREAD

**Issue by deviprasad135** [smiths/caseStudies#45]
In section 6.2.1 assumption 1, I think it would be clear if the points 1,2 and 3 are mentioned separately rather than mentioning them as a single paragraph.
![assumption 1](https://user-images.githubusercontent.com/30101689/39760443-4dfb550e-52a3-11e8-913f-137d4070abe9.PNG)

**Comment by smiths** [comment]
@deviprasad135, thank you for the feedback, but I don't think we can split this assumption.  You are correct that we want assumptions to be as atomic as possible, but this is an "or" assumption not an "and" assumption.  One of the cases 1 - 3 is applies, but we don't need to know which one.  We cannot list each case individually, since that would mean a contradiction.  A sheet of glass cannot be most simply supported and a cantilever.
