### ISSUE TITLE
Game Physics: Table Formatting

### ISSUE THREAD

**Issue by Mornix** [smiths/caseStudies#51]
(Issue #29)

In the [Game Physics SRS](https://github.com/smiths/caseStudies/blob/master/CaseStudies/gamephys/documentation/SRS/GamePhysicsSRS.pdf) there are a few tables where trying to highlight a row of text instead highlights the cells' columns as well to form an "area" of highlighting.

Expected highlighting behaviour:
<img width="414" alt="screen shot 2018-05-04 at 10 00 35 am" src="https://user-images.githubusercontent.com/1929800/39632246-8b24f710-4f82-11e8-9850-7bcf9db9841c.png">

Highlighting behaviour observed in the tables mentioned below:
<img width="731" alt="screen shot 2018-05-04 at 10 00 23 am" src="https://user-images.githubusercontent.com/1929800/39632242-893e67f6-4f82-11e8-8be3-3d386b7e8adc.png">

Tables with unexpected highlighting behaviour:
- [ ] Section 1.2 Table of Symbols
- [ ] Section 4.2.6 (Table 1)
- [ ] Section 4.2.6 (Table 2)

**Comment by smiths** [comment]
This is an interesting observation.  To be honest, I don't think I would ever have noticed, but it is true that the example you show is counter-intuitive.  I would guess that it has something to do with how the tables are built on LaTeX.  I have no idea how to fix this.  Do you?

**Comment by smiths** [comment]
@Mornix thank you for the investigation.  This obviously isn't an easy fix.  Do the tables in the generated (Drasil) version of the game physics documentation have the same problem?  If the generated version doesn't have this problem, then I think we can stop worrying about it.  In the long run we will stop maintaining the manual version in favour of the Drasil version.

**Comment by Mornix** [comment]
I took a quick look at the Drasil version and it does not use `siunitx` but does have some tables (for gamephys) which do have this "incorrect" selection.

**Comment by smiths** [comment]
Thank you for the information.  Thinking about it, this issue is probably better applied to the generated (Drasil) code.  Given that the LaTeX code is different from the manual and generated, even if you fix the manual version, the generated will still be broken.  If you are going to devote energy and time to this, it would be better invested in the generated version.  I suggest that you create a new issue in the Drasil repo for this, and close this one with a pointer to the new issue.
