### ISSUE TITLE
SolarHeatingWaterOnly_MG: Incorrect Documentation

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#55]
The MG document in SolarHeatingWaterOnly has the MG document of the SWHS repository which has PCM incorporated rather than simply water. This should be replaced by the documentation for SWHS without PCM.

**Comment by smiths** [comment]
Good catch @elwazana.  Please proceed with modifying the MG example so that it does not mention PCM.  When the document is done, you can close this issue.  When you close the issue, please include the hash code for the commit where the revised MG was committed.  That is, provide the hash code for the commit the closes the issue.

**Comment by elwazana** [comment]
220c839436f38aaf2c87c4020d0ca23a278fa6c0

**Comment by elwazana** [comment]
I'm sorry the above commit is just fixing a typo in the newly created MG.tex, the following commit is the correct one with the correspondeing change for this issue.

37229a7bbe9a2af212336ed8e5231416689e316d
