### ISSUE TITLE
GlassBR: Unclear Documentation in calculations.py

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#66]
On lines 74-80 of caseStudies/CaseStudies/glass/Implementations/Python/Implementation/calculations.py, the function `calc_lr` returns `lr` and `nfl`. I might very well be misunderstanding the return statement, but it seems like the function should be renamed to make it more clear, perhaps to `calc_lr_nfl`, and the comment on line 76 should reflect this as well. 

https://github.com/smiths/caseStudies/blob/a7e8172200744cf297aab9ab861c72a2befda9d7/CaseStudies/glass/Implementations/Python/Implementation/calculations.py#L74-L80

**Comment by smiths** [comment]
Good catch.

We can close this issue now because we are no longer maintaining the original Python version.  The simplified version does not make this mistake.  By the way, the solution used in the current (simplified) version of the Python code is my preference: there are now 2 functions, one for nfl and one for lr.
