### ISSUE TITLE
Incorrect README Instructions

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#77]
In caseStudies/CaseStudies/glass/README.md, it says:

> -------How to run the code and tests-------
> 
> To run the code: Go to /glass and type "make" at the prompt....
> To run the tests: Go to /glass and type "make test" at the prompt....
> To generate the documents: Go to /glass and type "make doc" at the prompt.
> To remove all the generated files and directories: Go to /glass and type "make clean" at the prompt.
> To do all of the above in one step: Go to /glass and type "make all" at the prompt.

However, there is no Makefile in /glass, although they are located at:

caseStudies/CaseStudies/glass/Implementations/C/Makefile
caseStudies/CaseStudies/glass/Implementations/Python/Makefile
caseStudies/CaseStudies/glass/Implementations/Python_Simplified/Makefile

**Comment by smiths** [comment]
Good catch.  The README.md file you reference is the instructions for the Python versions.  Can you please move this file to the Python examples.  For now, since we have both Python and Python_Simplified, you should have a copy for both of them.  You should also create a version of README.md for the C version.

**Comment by smiths** [comment]
Right.  I don't think we need branches with the case studies.

**Comment by samm82** [comment]
@smiths I'm not sure if I got all the descriptions of files right, so I'm not going to close this issue quite yet.

**Comment by smiths** [comment]
The descriptions look fine to me.
