### ISSUE TITLE
Symbol Ambiguity (E vs E) in SSP

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#98]
Moved the following over from #39:
***
 _E_ is used to denote both elastic modulus and interslice normal force, results in ambiguity (https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L166-L169)

The interslice force should have a subscript.  This should help a bit with the ambiguity.  In the long run, a symbol other than E should be used for the interslice force.  E for Young's modulus is so standard that it would be a mistake to change it, but the interslice force can be with any a symbol, likely a different alphabetical character that isn't used elsewhere.
***

**Comment by niazim3** [comment]
Would it be better to perhaps implement the new letter now instead of later?

$E$ is used quite often throughout the whole document, so a lot would need to be updated:

Interslice Normal force symbols:
- [ ] GD5
- [ ] GD8
- [ ] DD12
- [ ] Resistive Shear Force, w/o the influence of interslice forces derivation
- [ ] Mobile Shear Force, w/o the influence of interslice forces derivation
- [ ] DD18
- [ ] DD19
- [ ] Instance Models section
- [ ] Before IM3
- [ ] Interslice Force Derivation

Ambiguous occurrences:
- [ ] IM4
- [ ] Data constraints table

Elastic modulus:
- [ ] Under funcitonal requirements

**Comment by niazim3** [comment]
Lowercase p is used to denote pressure and capital P denotes resistive shear force.

Lowercase x is used to refer to X Ordinate and uppercase x is used to refer to Interslice Shear Force.

Some letters (uppercase and lowercase) that are available for use to be a symbol for the interslice normal force are : d, g, j, l, o.

That another character (Greek) can be used?

**Comment by smiths** [comment]
Thank you for the investigation @niazim3.  Let's use G.  (For some reason Greek letters aren't used that often to denote forces.)

**Comment by niazim3** [comment]
As for the figure update that is necessary, shall I

- rename this issue to be for that change (i.e. Update SSP Force Diagram for Symbol Change)
- leave a message in the readme

?

**Comment by smiths** [comment]
Rather than rename this issue, why don't you close it and create a new issue for updating the figure.  We should eventually fix the figure, but it is a low priority, especially since redrawing the figure will take time.  As far as I can tell the original source for the figure is missing, so that means building it from scratch.  (I had a quick look at it and I don't think editing the current png file would be easy or satisfactory.)  If we should redraw the picture, we should try draw.io.  I've used it recently, and I believe we can save the xml (?) file for future editing.

As a temporary fix, rather than a note in the README file a note with the caption for the figure might be more effective.  If we say that in the figure G has been relabelled as E, the document will technically be correct.

**Comment by niazim3** [comment]
Should the note-under-the-figure change be propagated to Drasil? (Also, as a rule, should most changes for this repo be propagated to Drasil or is it better to inquire about each one?)

**Comment by smiths** [comment]
Yes and yes.  😄 This change, and future changes to the manual version, should be propagated to Drasil.  If in doubt, or if there seems to be a potential problem, we should discuss it, but in general, we want the Drasil version and the manual case study version to match.  At some point we will stop maintaining the manual versions, but Drasil isn't ready yet for this step.

**Comment by niazim3** [comment]
This issue can now be closed.

**Comment by smiths** [comment]
Great.
